os: linux

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  
install:
  -pip install -r requirements-dev.txt
  
scripts:
  -python -m unittest discover
  
branches:
  only:
    - master
    
services:
  - docker
  
app:
  - flask-app